feat: group authorization
kubesphere/kubesphere pull request #3023
Opened 2020-10-16 04:46 UTC by RolandMa1986

Signed-off-by: Roland.Ma <rolandma@yunify.com>

**What type of PR is this?**
 /kind feature

**What this PR does / why we need it**:
Add group and groupbinding crds, generated clientset.

Fixes #

**Special notes for reviewers**:
```
```

**Additional documentation, usage docs, etc.**:
https://github.com/kubesphere/community/blob/82573c078ba5d5db031fbf9a663968508f809e92/sig-multitenancy/concepts-and-designs/user-group-designs.md

```docs

```
/assign @wansir  @zryfish

2020-10-19 03:00 UTC, RolandMa1986 commented
/assign @wansir

2020-10-19 03:01 UTC, RolandMa1986 commented
/assign @zryfish

2020-10-20 02:44 UTC, wansir requested changes

2020-10-20 02:44 UTC, wansir commented on pkg/apis/iam/v1alpha2/groupbinding_types.go
> +type Ref struct {
`iamv1alpha2.GroupRef` is more clear.

2020-10-21 10:13 UTC, wansir commented
/lgtm

2020-10-21 11:10 UTC, zryfish commented
Isn't this PR WIP? Just found CRD definitions, no controller code

2020-10-21 14:01 UTC, RolandMa1986 commented
> Isn't this PR WIP? Just found CRD definitions, no controller code

This feature is splited into a few small commits, this is part of it.

2020-10-22 07:43 UTC, zryfish commented
/approve

2020-10-23 01:16 UTC, RolandMa1986 commented
/lgtm

2020-10-23 02:17 UTC, wansir commented
/lgtm
/approve

2020-10-23 02:26 UTC, merged