feature: custom alerting
kubesphere/kubesphere pull request #3181
Opened 2020-12-04 03:33 UTC by junotx

**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

Custom alerting with prometheus style is introduced

2020-12-04 06:03 UTC, junotx commented
/cc @benjaminhuo

2020-12-08 10:05 UTC, zryfish commented
This is a huge PR, is there any issues and design documentation for reviewers? And please add more comments to your code, it's read friendly for others.

2020-12-08 11:14 UTC, benjaminhuo commented
Related issue: https://github.com/kubesphere/kubesphere/issues/3065

2020-12-11 06:37 UTC, benjaminhuo commented
There will be some changes to the implementation, so please hold on reviewing this PR

2020-12-26 14:20 UTC, junotx commented
Now it is ready for review @benjaminhuo

2020-12-29 09:46 UTC, benjaminhuo requested changes

2020-12-29 09:46 UTC, benjaminhuo commented on pkg/api/customalerting/v1alpha1/types.go
> +type AlertingRuleProps struct {
As discussed we can adjust AlertingRuleProps PostableAlertingRule GettableAlertingRule as below:
- AlertingRuleProps => AlertingRule
- Move common properties like Alias and Description to AlertingRule
- Move name and id in AlertingRuleQualifier to AlertingRule
- PostableAlertingRule could be replaced by AlertingRule
- Custom and Level could be removed from AlertingRuleQualifier
- Change Rule *AlertingRuleQualifier in Alerts to RuleId and RuleName

2020-12-30 10:58 UTC, benjaminhuo requested changes

2020-12-30 10:58 UTC, benjaminhuo commented on pkg/kapis/customalerting/v1alpha1/handler.go
> +func (h *handler) handleListBuiltinSpecifiedRuleAlerts(req *restful.Request, resp *restful.Response) {
handleListBuiltinSpecifiedRuleAlerts 
=>
handleListBuiltinRuleAlerts

2020-12-30 10:58 UTC, benjaminhuo commented on pkg/kapis/customalerting/v1alpha1/handler.go
> +	alerts, err := h.operator.ListBuiltinSpecifiedRuleAlerts(req.Request.Context(), ruleId)
ListBuiltinSpecifiedRuleAlerts
=>
ListBuiltinRuleAlerts

2020-12-30 10:58 UTC, benjaminhuo commented on pkg/models/customalerting/customalerting.go
> +		lblStrings := strings.Split(option.ThanosRuleResourceLabels, ",")
lblStrings = > labels
lblString => label
lbl => l

2020-12-31 11:51 UTC, benjaminhuo requested changes

2020-12-31 11:51 UTC, benjaminhuo commented on pkg/models/customalerting/rules/utils.go
> +func MixAlertingRules(ruleNamespace string, ruleChunk *ResourceRuleChunk, epRuleGroups []*customalerting.RuleGroup,
to be more clear, maybe we can rename MixAlertingRules/MixAlertingRule/mixAlertingRule to GetAlertingRulesStatus/GetAlertingRuleStatus/getAlertingRuleStatus ?

2020-12-31 11:52 UTC, benjaminhuo commented
This is indeed a PR with lots of efforts, thanks @junotx 
Pls make some minor changes as the comments above, thanks again.

2021-01-04 07:12 UTC, junotx commented on pkg/api/customalerting/v1alpha1/types.go
> +	Total int                     `json:"total"`
It is for paging

2021-01-04 07:22 UTC, junotx commented on pkg/models/customalerting/customalerting.go
> +		lblStrings := strings.Split(option.ThanosRuleResourceLabels, ",")
These names will remain because a package called labels has been imported

2021-01-06 03:40 UTC, benjaminhuo commented on pkg/models/customalerting/customalerting.go
> +		lblStrings := strings.Split(option.ThanosRuleResourceLabels, ",")
ok

2021-01-07 09:10 UTC, benjaminhuo approved these changes
looks better
Please resolve the conflicts @junotx 

And we can set maxConfigMapDataSize to be larger than 0.3

2021-01-08 05:30 UTC, benjaminhuo approved these changes
/lgtm

2021-01-08 05:31 UTC, benjaminhuo commented
/assign @zryfish

2021-01-08 05:55 UTC, benjaminhuo commented
The previous alerting uses alerting.kubesphere.io/v1 , @junotx pls considering changing customalerting.kubesphere.io/v1alpha1 to alerting.kubesphere.io/v2alpha1 in a new PR if it's feasible

2021-01-11 06:21 UTC, benjaminhuo commented on pkg/apiserver/config/config.go
> +	CustomAlertingOptions *customalerting.Options                    `json:"customalerting,omitempty" yaml:"customalerting,omitempty" mapstructure:"customalerting"`
the option should be combined with the original alert option when changing customalerting.kubesphere.io/v1alpha1 to alerting.kubesphere.io/v2alpha1. @junotx

2021-01-11 09:55 UTC, junotx commented on pkg/apiserver/config/config.go
> +	CustomAlertingOptions *customalerting.Options                    `json:"customalerting,omitempty" yaml:"customalerting,omitempty" mapstructure:"customalerting"`
This adjustment was discussed yesterday and will be changed in a new pr

2021-01-12 11:11 UTC, benjaminhuo requested changes

2021-01-12 11:11 UTC, benjaminhuo commented on pkg/simple/client/alerting/options.go
> +		"The labels will be added to prometheusrule custom resources to be selected by thanos ruler. eg: thanosruler=thanos-ruler,role=custom-alerting-rules (for the alerting with v2alpha1 version or highe
The labels will be added to prometheusrule custom resources to be selected by thanos ruler =>
Labels used by Thanos Ruler to select PrometheusRule custom resources

2021-01-12 11:11 UTC, benjaminhuo commented on pkg/simple/client/alerting/options.go
> +		"alerting server endpoint for the alerting with v1 version.")
alerting with v1 version =>
alerting v1

2021-01-13 11:00 UTC, benjaminhuo approved these changes
/lgtm

2021-01-15 02:49 UTC, zryfish commented on cmd/ks-apiserver/app/options/options.go
> +			return nil, fmt.Errorf("failed to init alerting client")
should return error `err` as well

2021-01-18 01:21 UTC, benjaminhuo approved these changes
/lgtm

2021-01-18 02:18 UTC, zryfish commented
/approve

Please verify as soon as possible

2021-01-18 02:19 UTC, merged