support for querying pods metrics from the cluster level
kubesphere/kubesphere pull request #3186
Opened 2020-12-08 03:02 UTC by junotx

**What type of PR is this?**

/kind api-change

**What this PR does / why we need it**:

support for querying pods monitoring metrics from the cluster level

/area monitoring
/cc @benjaminhuo

2020-12-08 10:10 UTC, zryfish commented
I believe this api can only be called by cluster administrators. @wansir Can the current authorization framework cover this API?

2020-12-08 10:35 UTC, benjaminhuo requested changes

2020-12-08 10:35 UTC, benjaminhuo commented on pkg/simple/client/monitoring/prometheus/promql.go
> +		podSelector = fmt.Sprintf(`pod=~"%s"`, o.ResourceFilter)
Please add an entry in promql_test.go for unit test

2020-12-08 10:36 UTC, benjaminhuo commented
> I believe this api can only be called by cluster administrators. @wansir Can the current authorization framework cover this API?

should be similar to call API for node's pods

2020-12-09 02:41 UTC, benjaminhuo commented
/lgtm

2020-12-09 02:41 UTC, benjaminhuo approved these changes

2020-12-10 06:37 UTC, zryfish commented
/approve

2020-12-10 06:38 UTC, merged