fix bug get goroutine for audit timeout
kubesphere/kubesphere pull request #3201
Opened 2020-12-14 03:49 UTC by wanjunlei

Signed-off-by: wanjunlei <wanjunlei@yunify.com>

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Now the limit of goroutines that send audit events to webhook is small and can not be customized,  if there are so many requests, this will cause an error that `get goroutine for audit timeout`, the audit event will sending failed. 
This pr will increase the default limit of goroutines from 10 to 100, and allow the user to customize it with an argument named `auditing-goroutines-num`.
In addition, the audit events will be aggregated and sent to increase the efficiency of sending. Users can customize the size of events in one batch with the argument `auditing-batch-max-size`, and the interval of two batches with the argument `auditing-batch-max-wait`.

2020-12-14 04:44 UTC, wanjunlei commented
/assign @benjaminhuo 
/assign @zryfish

2020-12-14 06:44 UTC, benjaminhuo requested changes

2020-12-14 06:44 UTC, benjaminhuo commented on pkg/simple/client/auditing/elasticsearch/options.go
> +	fs.DurationVar(&s.MaxBatchWait, "auditing-batch-max-wait", c.MaxBatchWait,
auditing-batch-max-wait => auditing-event-batch-interval

2020-12-14 06:44 UTC, benjaminhuo commented on pkg/simple/client/auditing/elasticsearch/options.go
> +		"The max size of the auditing event in a batch.")
The max size of the auditing event in a batch. => The batch size of auditing events

2020-12-14 06:44 UTC, benjaminhuo commented on pkg/simple/client/auditing/elasticsearch/options.go
> +		"The number of goroutines which send auditing events to webhook.")
The number of goroutines which send auditing events to webhook. => The maximum concurrent senders which send auditing events to the auditing webhook

2020-12-14 06:44 UTC, benjaminhuo commented on pkg/simple/client/auditing/elasticsearch/options.go
> +		"MaxBatchWait indicates the maximum interval between two batches.")
MaxBatchWait indicates the maximum interval between two batches. => The batch interval of auditing events.

2020-12-14 06:44 UTC, benjaminhuo commented on pkg/simple/client/auditing/elasticsearch/options.go
> +	MaxBatchSize int `json:"batchSize" yaml:"batchSize"`
MaxBatchSize => EventBatchSize

2020-12-14 06:44 UTC, benjaminhuo commented on pkg/apiserver/auditing/backend.go
> +			klog.Error("get goroutine timeout")
get goroutine timeout => Get auditing event sender timeout

2020-12-14 06:44 UTC, benjaminhuo commented on pkg/apiserver/auditing/backend.go
> +			klog.V(6).Infof("json marshal error, %s", err)
Should be error log level, not info

2020-12-14 06:44 UTC, benjaminhuo commented on pkg/apiserver/auditing/backend.go
> +		klog.V(8).Infof("%s", string(bs))
should be debug level log？

2020-12-14 06:44 UTC, benjaminhuo commented on pkg/apiserver/auditing/backend.go
> +	WaitTimeout          = time.Second
WaitTimeout => GetSenderTimeout

2020-12-14 06:45 UTC, benjaminhuo commented
This PR looks good, variable names need to be adjusted

2020-12-14 13:30 UTC, benjaminhuo approved these changes
/lgtm

2020-12-15 03:47 UTC, zryfish commented
Is there any load test data on this PR?

2020-12-21 09:26 UTC, zryfish commented
/cc @wanjunlei  I think we'd better do a load testing before merge this PR.

2020-12-22 03:22 UTC, wanjunlei commented
I had test it in an all in one cluster with 8c and 16g, use 1000 thread to call the  API `clusters/{cluster}/components`,  with the default config, `auditing-event-senders-num` is 100, `auditing-event-batch-size` is 100, `auditing-event-batch-interval` is 3s,  the audit log send to the audit webhook successfully.

2020-12-28 05:54 UTC, zryfish commented
/approve

2020-12-28 05:55 UTC, merged