fix metrics query bug for pods with duplicate name in one node
kubesphere/kubesphere pull request #3224
Opened 2020-12-23 03:21 UTC by junotx

**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

fix metrics query bug for pods with duplicate name in one node

/area monitoring
/cc @benjaminhuo

2020-12-23 11:56 UTC, benjaminhuo requested changes

2020-12-23 11:56 UTC, benjaminhuo commented on pkg/simple/client/monitoring/prometheus/promql.go
> +				resourcesFilter = fmt.Sprintf("(%s)|(%s)", resourcesFilter, strings.Join(pods, "|"))
/pods API is newly added, do we still need to add the content of old resourcesFilter to the content of namespacedResourceFilter ?

It's ok to do so for /nodes/{node}/pods API for backward-compatible.

2020-12-24 02:07 UTC, junotx commented on pkg/kapis/monitoring/v1alpha3/register.go
> +		Doc("Get pod-level metric data of a specific pod. Navigate to the pod by the node where it is scheduled. deprecated: please use `/namespaces/{namespace}/pods/{pod}` instead.").
There is no `/pods/{pod}`

2020-12-24 03:16 UTC, benjaminhuo commented on pkg/kapis/monitoring/v1alpha3/register.go
> +		Doc("Get pod-level metric data of a specific pod. Navigate to the pod by the node where it is scheduled. deprecated: please use `/namespaces/{namespace}/pods/{pod}` instead.").
I mean the new added  /pods API should be able to get metrics for a specific pod, so the desc could be changed to 

Deprecated: please use /namespaces/{namespace}/pods/{pod} or /pods ?

2020-12-24 09:02 UTC, benjaminhuo approved these changes
/lgtm

2020-12-28 06:11 UTC, zryfish commented
/cc @benjaminhuo  Can review this PR again cause there are new changes made

2020-12-28 06:13 UTC, benjaminhuo commented
/lgtm

2020-12-28 06:36 UTC, benjaminhuo approved these changes

2021-01-06 01:47 UTC, zryfish commented
/approve

2021-01-06 01:52 UTC, zryfish commented
/unapprove

@junotx  conflicts

2021-01-08 06:00 UTC, benjaminhuo commented
/lgtm

2021-01-08 06:01 UTC, benjaminhuo approved these changes

2021-01-08 06:01 UTC, merged