Add kubeedge API
kubesphere/kubesphere pull request #3427
Opened 2021-03-03 09:34 UTC by Ma-Dan

Signed-off-by: root <danma@yunify.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
/kind feature
> /kind flake

**What this PR does / why we need it**:
Add KubeEdge API support to console for edge functions

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for reviewers**:
```
```

**Additional documentation, usage docs, etc.**:

```docs

```

2021-03-05 01:50 UTC, benjaminhuo requested changes

2021-03-05 01:50 UTC, benjaminhuo commented on pkg/simple/client/kubeedge/options.go
> +	fs.StringVar(&o.Endpoint, "edge-server-endpoint", c.Endpoint,
edge-server-endpoint => edge-watcher-endpoint

2021-03-05 01:50 UTC, benjaminhuo commented on pkg/simple/client/kubeedge/options.go
> +		"edge server endpoint for edge v1alpha1.")
edge watcher endpoint.

2021-03-05 02:44 UTC, Ma-Dan commented on pkg/simple/client/kubeedge/options.go
> +	fs.StringVar(&o.Endpoint, "edge-server-endpoint", c.Endpoint,
Fixed

2021-03-05 02:44 UTC, Ma-Dan commented on pkg/simple/client/kubeedge/options.go
> +		"edge server endpoint for edge v1alpha1.")
Fixed

2021-03-05 02:54 UTC, benjaminhuo approved these changes

2021-03-05 02:55 UTC, benjaminhuo commented
/lgtm

2021-03-05 08:30 UTC, zryfish commented
@Ma-Dan conflict, please help reslove first

2021-03-05 08:55 UTC, Ma-Dan commented
> @Ma-Dan conflict, please help reslove first

Rebased

2021-03-05 09:03 UTC, Ma-Dan commented
/assign zryfish

2021-03-08 08:40 UTC, zryfish commented
CI failed, please use a real kubeedge options @Ma-Dan

2021-03-08 11:24 UTC, zryfish commented
/lgtm
/approve

2021-03-08 11:24 UTC, merged