Request edge metrics only if prometheus metrics data is empty
kubesphere/kubesphere pull request #3594
Opened 2021-03-26 02:42 UTC by zhu733756

Signed-off-by: zhu733756 <talonzhu@yunify.com>

**What type of PR is this?**
> /kind feature

**What this PR does / why we need it**:
Request edge metrics only if prometheus metrics data is empty. Currently, it requests the edge metrics everytime.

**Which issue(s) this PR fixes**:

Fixes # 

**Special notes for reviewers**:
```

```

**Additional documentation, usage docs, etc.**:

```docs

```

2021-03-26 03:13 UTC, benjaminhuo requested changes

2021-03-26 03:13 UTC, benjaminhuo commented on pkg/models/monitoring/monitoring.go
> +			metircName := ressMetric.MetricName
metircName => metricsName

2021-03-26 03:13 UTC, benjaminhuo commented on pkg/models/monitoring/monitoring.go
> +			metircName := ressMetric.MetricName
metircName => metricName

2021-03-26 03:19 UTC, zhu733756 commented on pkg/models/monitoring/monitoring.go
> +			metircName := ressMetric.MetricName
fixed

2021-03-26 03:19 UTC, zhu733756 commented on pkg/models/monitoring/monitoring.go
> +			metircName := ressMetric.MetricName
fixed

2021-03-26 03:26 UTC, benjaminhuo approved these changes
/lgtm

2021-03-26 03:26 UTC, benjaminhuo commented
/assign @zryfish

2021-03-29 00:34 UTC, zryfish commented
/approve

2021-03-29 00:35 UTC, merged