Update README_zh.md
kubesphere/kubesphere pull request #4402
Opened 2021-10-31 15:21 UTC by Lnek

typo

### What type of PR is this?

### What this PR does / why we need it:

### Which issue(s) this PR fixes:

Fixes #

### Special notes for reviewers:
```
```

### Does this PR introduced a user-facing change?

```release-note

```

### Additional documentation, usage docs, etc.:

```docs

```

2021-10-31 15:23 UTC, FeynmanZhou commented on README_zh.md
> +  提供集中控制平台来管理多个 Kubernetes 集群，支持将应用程序发布到跨不同云供应商的多个k8s集群上。
多个 K8s 集群上。

2021-10-31 15:24 UTC, FeynmanZhou requested changes
Thanks for your PR! Please see my comments : )

2021-11-01 13:49 UTC, LinuxSuRen reviewed
Thanks for your contribution. But please review the PR template again.

![image](https://user-images.githubusercontent.com/1450685/139681952-4fc67b3b-d4f3-4b4e-84fb-fbf71792a955.png)

2021-11-01 13:50 UTC, LinuxSuRen commented
/retitle Typo fixing in the README_zh.md file

2021-11-04 02:53 UTC, FeynmanZhou commented
@Lnek Could you update it according to the comment above?

2021-11-10 09:31 UTC, Lnek commented
@FeynmanZhou done

2021-11-10 13:08 UTC, FeynmanZhou commented
/lgtm
/approve

2021-11-22 02:00 UTC, zryfish commented
/approve

2021-11-22 02:09 UTC, merged