add alerting v2beta1 apis
kubesphere/kubesphere pull request #5115
Opened 2022-08-03 03:36 UTC by junotx

### What type of PR is this?

/kind feature

### What this PR does / why we need it:

alerting v2beta1 apis will operate the resources of `RuleGroup`, `ClusterRuleGroup`, `GlobalRuleGroup` objects: 
- all common operations may call the k8s apis for these resources.
- getting status and alerts of the rules may call the ks apis which this pr contains.

### Which issue(s) this PR fixes:

Fixes #

### Special notes for reviewers:
```
```

### Does this PR introduced a user-facing change?

```release-note
Add alerting v2beta1 apis based on rulegroups resources
```

### Additional documentation, usage docs, etc.:

```docs

```

2022-08-03 10:34 UTC, benjaminhuo requested changes

2022-08-03 10:34 UTC, benjaminhuo commented on pkg/api/alerting/v2beta1/types.go
> +	LastEvaluation *time.Time   `json:"lastEvaluation,omitempty" description:"time for last evaluation"`
```suggestion
	LastEvaluation *time.Time   `json:"lastEvaluation,omitempty" description:"time of last evaluation"`
```

2022-08-03 10:34 UTC, benjaminhuo commented on pkg/api/alerting/v2beta1/types.go
> +	RuleStatuses   []RuleStatus `json:"ruleStatuses,omitempty" description:"rule statuses"`
```suggestion
	RulesStatus   []RuleStatus `json:"rulesStatus,omitempty" description:"status of rules in one RuleGroup"`
```

2022-08-03 10:34 UTC, benjaminhuo commented on pkg/api/alerting/v2beta1/types.go
> +	State          string       `json:"state,omitempty" description:"state of a rule based on its alerts, one of firing, pending, inactive"`
```suggestion
	State          string       `json:"state,omitempty" description:"state of a rule, one of firing, pending or inactive depending on its alerts"`
```

2022-08-03 10:34 UTC, benjaminhuo commented on pkg/api/alerting/v2beta1/types.go
> +	State                     string     `json:"state,omitempty" description:"state of a rule based on its alerts, one of firing, pending, inactive"`
```suggestion
	State                     string     `json:"state,omitempty" description:"state of a rule, one of firing, pending or inactive depending on its alerts"`
```

2022-08-03 10:34 UTC, benjaminhuo commented on pkg/api/alerting/v2beta1/types.go
> +	Health                    string     `json:"health,omitempty" description:"health state of a rule based on the last execution, one of ok, err, unknown"`
```suggestion
	Health                    string     `json:"health,omitempty" description:"health state of a rule, one of ok, err or unknown depending on the last evaluation result"`
```

2022-08-03 10:34 UTC, benjaminhuo commented on pkg/api/alerting/v2beta1/types.go
> +	LastError                 string     `json:"lastError,omitempty" description:"error for the last execution"`
```suggestion
	LastError                 string     `json:"lastError,omitempty" description:"error for the last evaluation"`
```

2022-08-03 10:34 UTC, benjaminhuo commented on pkg/api/alerting/v2beta1/types.go
> +	LastEvaluation            *time.Time `json:"lastEvaluation,omitempty" description:"time for last evaluation of query expression"`
```suggestion
	LastEvaluation            *time.Time `json:"lastEvaluation,omitempty" description:"time of the last evaluation of the query expression"`
```

2022-08-03 10:34 UTC, benjaminhuo commented on pkg/api/alerting/v2beta1/types.go
> +	ActiveAt    *time.Time        `json:"activeAt,omitempty" description:"time when alert is active"`
```suggestion
	ActiveAt    *time.Time        `json:"activeAt,omitempty" description:"time when this alert became active"`
```

2022-08-03 10:34 UTC, benjaminhuo commented on pkg/kapis/alerting/v2beta1/register.go
> +		Param(ws.QueryParameter(kapialertingv2beta1.FieldState, "state of a rulegroup based on its rules, one of `firing`, `pending`, `inactive`")).
```suggestion
		Param(ws.QueryParameter(kapialertingv2beta1.FieldState, "state of a rulegroup, one of `firing`, `pending`, `inactive` depending on its rules")).
```

2022-08-04 02:55 UTC, junotx commented on pkg/api/alerting/v2beta1/types.go
> +	EvaluationTime *float64     `json:"evaluationTime,omitempty" description:"taken seconds for evaluation"`
The `EvaluationTime`, refering to [prometheus api](https://github.com/prometheus/prometheus/blob/v2.36.0/web/api/v1/api.go#L1183), may not change

2022-08-04 05:37 UTC, benjaminhuo commented
/lgtm

2022-08-04 05:37 UTC, benjaminhuo commented
/approve

2022-08-04 05:38 UTC, merged